# Generated by Django 4.2.20 on 2025-03-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('READMISSION', 'Readmission Risk'), ('COST', 'Treatment Cost Prediction'), ('INVENTORY', 'Inventory Depletion Prediction'), ('APPOINTMENT', 'Appointment No-Show Prediction')], max_length=20)),
                ('prediction_value', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField()),
                ('features_used', models.JSONField()),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('feature_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['feature_name'], name='ml_system_f_feature_8e6be8_idx'), models.Index(fields=['patient'], name='ml_system_f_patient_fc103c_idx'), models.Index(fields=['medicine'], name='ml_system_f_medicin_e841a0_idx')],
            },
        ),
    ]
